version: '3.4'

services:

  gitlab:
    restart: always
    image: gitlab/gitlab-ce:9.1.0-ce.0
    hostname: $gitlab_host_name
    container_name: gitlab
    links:
      - postgresql
      - redis
    environment:
      external_common_mounts_path: $external_common_mounts_path
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://$gitlab_host_name:$gitlab_port'
        gitlab_rails['gitlab_shell_ssh_port'] = $gitlab_ssh_port
    ports:
      - "$gitlab_port:$gitlab_port"
      - "$gitlab_ssh_port:22"
    volumes:
      - ./mounts:$external_common_mounts_path
      - ./gitlab/mounts:$external_mounts_path
      - ./gitlab/conf/config:/etc/gitlab
      - ./gitlab/conf/logs:/var/log/gitlab
      - ./gitlab/conf/data:/var/opt/gitlab

  jenkins:
    restart: always
    build:
      context: ./jenkins
      args:
        - external_mounts_path=$external_mounts_path
        - jenkins_home_path=$jenkins_home_path
    container_name: jenkins
    expose:
      - "8080"
    ports:
      - "$jenkins_port:8080"
    links:
      - doc-server
    depends_on:
      - gitlab
    volumes:
      - ./mounts:$external_common_mounts_path
      - ./jenkins/mounts:$external_mounts_path
      - ./jenkins/conf:/var/jenkins_home
    environment:
      - jenkins_user=$jenkins_user
      - jenkins_pass=$jenkins_pass
      - jenkins_home_path=$jenkins_home_path
      - external_mounts_path=$external_mounts_path
      - external_common_mounts_path=$external_common_mounts_path
      - jenkins_add_credential_filename=$jenkins_add_credential_filename
      - gitlab_port=$gitlab_port
      - jenkins_executer_folder_name=$jenkins_executer_folder_name
    stdin_open: true
    tty: true

  mongodb:
    restart: always
    image: mongo
    container_name: mongodb
    links:
      - gitlab:gitlab
    volumes:
      - ./mongodb/conf:/data/db
      - ./mongodb/mounts:$external_mounts_path
    stdin_open: true
    tty: true

  mongodb-interface:
    restart: always
    image: mongo-express
    container_name: mongodb-interface
    ports:
      - "$mongodb_interface_port:8081"
    links:
      - mongodb:mongo
    depends_on:
      - mongodb
    volumes:
      - ./mongodb-interface/conf:/data/db
      - ./mongodb-interface/mounts:$external_mounts_path
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=$mongodb_interface_user
      - ME_CONFIG_BASICAUTH_PASSWORD=$mongodb_interface_pass
    stdin_open: true
    tty: true

  doc-server:
    build: ./doc-server
    container_name: doc-server
    ports:
      - "$doc_server_port:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./mounts:$external_common_mounts_path
    environment:
      - external_mounts_path=$external_mounts_path
      - external_common_mounts_path=$external_common_mounts_path
    stdin_open: true
    tty: true

