
version: '3.4'

services:
  gitlab:
    restart: always
    image: gitlab/gitlab-ce
    hostname: 'gitlab.example.com'
    container_name: gitlab
    expose:
      - "80"
      - "22"
      - "443"
    ports:
      - "80:80"
      - "22:22"
      - "443:443"
    volumes:
      - "./gitlab/conf/config:/etc/gitlab"
      - "./gitlab/conf/logs:/var/log/gitlab"
      - "./gitlab/conf/data:/var/opt/gitlab"

  jenkins:
    restart: always
    build:
      context: ./jenkins
    container_name: jenkins
    links:
      - gitlab
    expose:
      - "8080"
    ports: 
      - "5002:8080"
    volumes: 
      - ./jenkins/mounts:/var/external-mounts
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    stdin_open: true
    tty: true

  docserver:
    restart: always
    build: ./docserver
    container_name: docserver
    expose:
      - "3000"
    ports: 
      - "3002:3000"
    volumes: 
      - ./docserver/mounts:/var/external-mounts
    stdin_open: true
    tty: true