version: '3.4'

services:
  redis:
    restart: always
    image: redis:3.0.7-alpine
    container_name: redis

  postgresql:
    restart: always
    image: postgres:9.6.2-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - ./postgresql/conf:/var/lib/postgresql

  gitlab:
    restart: always
    image: gitlab/gitlab-ce:9.1.0-ce.0
    hostname: 'gitlab.example.com'
    container_name: gitlab
    links:
      - postgresql:postgresql
      - redis:redis
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "gitlab"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        external_url 'http://gitlab.example.com:30080'
        gitlab_rails['gitlab_shell_ssh_port'] = 30022
    ports:
      - "30080:30080"
      - "30022:22"
    volumes:
      - ./gitlab/conf/config:/etc/gitlab
      - ./gitlab/conf/logs:/var/log/gitlab
      - ./gitlab/conf/data:/var/opt/gitlab

  jenkins:
    restart: always
    build:
      context: ./jenkins
    container_name: jenkins
    depends_on:
      - gitlab
    links:
      - gitlab
    expose:
      - "8080"
    ports:
      - "5002:8080"
    volumes:
      - ./jenkins/mounts:/var/external-mounts
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    stdin_open: true
    tty: true

  docserver:
    restart: always
    build: ./docserver
    container_name: docserver
    expose:
      - "3000"
    ports:
      - "3002:3000"
    volumes:
      - ./docserver/mounts:/var/external-mounts
    stdin_open: true
    tty: true
