version: '3.4'

services:
  jenkins:
    restart: always
    build:
      context: ./jenkins
      args:
        - external_mounts_path=$external_mounts_path
        - jenkins_home_path=$jenkins_home_path
    container_name: jenkins
    expose:
      - "8080"
    ports:
      - "$jenkins_port:8080"
    volumes:
      - ./jenkins/mounts:$external_mounts_path
      - ./jenkins/conf:/var/jenkins_home
    environment:
      - jenkins_user=$jenkins_user
      - jenkins_pass=$jenkins_pass
      - jenkins_home_path=$jenkins_home_path
    stdin_open: true
    tty: true
