concurrent = 1
check_interval = 0

[[runners]]
  name = "Shared Gitlab Runner Token"
  url = "http://www.gitlab.cn:5000"
  token = "87897d2f79c3d8c28c2f0959574c3d"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = false
    disable_cache = true
    volumes = ["/cache"]
    network_mode = "host"
    shm_size = 0
  [runners.cache]
